name: fungifunate
channels: [conda-forge, bioconda, defaults]
dependencies:
  - python>=3.10
  - snakemake>=7
  - mamba
  - perl
  - salmon>=1.10
  - r-base>=4.3
  - r-tidyverse
  - r-ggplot2
  - r-data.table
  - bioconductor-deseq2
  - bioconductor-tximport
  - bioconductor-topgo
  - bioconductor-annotationdbi
  - bioconductor-go.db
  - bioconductor-biomart
  - r-enrichplot
  - r-clusterprofiler
  - r-viridis
  - r-optparse
